### ISSUE TITLE
No video output unless GPU patched rom file is specified

### ISSUE THREAD

**Issue by jukefr** [saveriomiroddi/vga-passthrough#24]
So I spent about 3 days (with no prior knowledge of pcie passthrough) trying to get this to work and I think I am on the right path.

The one thing that I spent the most time on I think was that everything would set up fine but when I started the VM and switched to the GPU hdmi I would have no video output.

Turns out that even though my card is compatible with EFI booting for some reason I still need to configure the romfile of the GPU in QEMU for it to work.

Simply appending `romfile=$VGA_ROM_FILE` to the `-device` line for the GPU fixes it.

This is a patched bios but I don't really know if the patch helped in any way, here's what I did :
- downloaded the bios for my card online
- opened in a hex editor and removed everything **before** the line which starts with `U.XXXX...` when you do a search for the utf-8 `VIDEO` keyword (forward search, starting from top)
- then ran this manually patched bios through https://github.com/Matoking/NVIDIA-vBIOS-VFIO-Patcher to bring it from 256k to 128k.

I have a GTX 1070Ti MSI Gaming.

I don't know if my experience will reflect many other people's, but I think it would be a great idea to have a bit mentioning this in the troubleshooting part. (at the very least I hope that this issue might help some in the future)

In the other things that can go wrong section I had some other problems mainly related to the fact that my motherboard bios was outdated. I needed the `allow_unsafe_interrupts=1 pcie_acs_override=downstream` grub boot params to get any output from the VM, however this resulted in an error code 43 for the GPU (by nvidia) on windows which pretty much rendered it unusable. I am currently in the process of trying to get rid of that error 43 without those grub parameters (updated motherboard bios) and a fresh install of the vm.
edit: yeah, works now, no error 43. Don't use the grub boot flags unless you want to debug stuff.

Cheers

**Comment by saveriomiroddi** [comment]
Hello!

Thanks for writing. Something that it's not 100% clear to me is, are you talking about system with an integrated GPU _and_ a discrete one, or only a discrete one?

Also, where you talk about the GRUB, you essentially did _not_ need any more parameters after updating the bios, correct? That's what I understand from your edit.

**Comment by saveriomiroddi** [comment]
Hello! I didn't receive any feedback for some time, so I'm closing the issue.

It's not clear if your attempt was performed on a single GPU system. In order to avoid any ambiguity, I've updated the documentation to make the target (two GPUs) clear.

In case you were working with two GPUs, feel free to reopen the issue.
