### ISSUE TITLE
Add OMVF build chapter.

### ISSUE THREAD

**Issue by saveriomiroddi** [saveriomiroddi/vga-passthrough#8]
Copy the post from the blog, in order to address QEMU 2.10 incompatibility.

**Comment by saveriomiroddi** [comment]
Addresses by #10 .

**Comment by schmitch** [comment]
Quick Question: is this incompatibility still the case for Ubuntu 17.10?

Actually apt shows the following:
```
schmitch@SHANGHAI-virt:~$ apt show ovmf
Package: ovmf
Version: 0~20170911.5dfba97c-1
```

**Comment by saveriomiroddi** [comment]
Hello! I will check in the next days, and get back to you.

It should be trivial to test, by going through the log of the EDK github repo, and checking the commit from the package name against the date when I've added the chapter :smile:

**Comment by saveriomiroddi** [comment]
@schmitch I'm closing this issue, and tracking your request on a new one (#11).
